params ["_vehicle"];
_vehicle setPylonLoadout [1,"USAF_PylonRack_7Rnd_APKWS", true];
_vehicle setPylonLoadout [2,"USAF_PylonRack_21Rnd_HYDRA70", true];
_vehicle setPylonLoadout [3,"USAF_PylonRack_2Rnd_AGM65E", true];
_vehicle setPylonLoadout [4,"itc_hp_dumb_rocket_itc_ammo_Hydra_M257", true];
_vehicle setPylonLoadout [5,"itc_hp_dumb_rocket_itc_ammo_Hydra_M156", true];
_vehicle setPylonLoadout [6,"USAF_PylonRack_1Rnd_GBU24", true];
_vehicle setPylonLoadout [7,"itc_hp_dumb_rocket_itc_ammo_Hydra_M156", true];
_vehicle setPylonLoadout [8,"itc_hp_dumb_rocket_itc_ammo_Hydra_M257", true];
_vehicle setPylonLoadout [9,"USAF_PylonRack_2Rnd_AGM65E", true];
_vehicle setPylonLoadout [10,"USAF_PylonRack_21Rnd_HYDRA70", true];
_vehicle setPylonLoadout [11,"USAF_PylonRack_7Rnd_APKWS", true];