params ["_vehicle"];
_vehicle setPylonLoadout [1,"USAF_PylonRack_2Rnd_AIM9X_LAU105", true];
_vehicle setPylonLoadout [2,"USAF_PylonRack_7Rnd_APKWS", true];
_vehicle setPylonLoadout [3,"USAF_PylonRack_2Rnd_AGM65E", true];
_vehicle setPylonLoadout [4,"USAF_PylonRack_1Rnd_MK84", true];
_vehicle setPylonLoadout [5,"USAF_PylonRack_1Rnd_MK84", true];
_vehicle setPylonLoadout [6,"USAF_PylonRack_1Rnd_GBU24", true];
_vehicle setPylonLoadout [7,"USAF_PylonRack_1Rnd_MK84", true];
_vehicle setPylonLoadout [8,"USAF_PylonRack_1Rnd_MK84", true];
_vehicle setPylonLoadout [9,"USAF_PylonRack_2Rnd_AGM65E", true];
_vehicle setPylonLoadout [10,"USAF_PylonRack_7Rnd_APKWS", true];
_vehicle setPylonLoadout [11,"itc_hp_bru61_itc_ammo_gbu39", true];