params ["_vehicle"];
_vehicle setPylonLoadout [1,"PylonRack_1Rnd_Missile_AA_04_F", true];
_vehicle setPylonLoadout [2,"PylonRack_1Rnd_Missile_AA_04_F", true];
_vehicle setPylonLoadout [3,"PylonMissile_1Rnd_Mk82_F", true];
_vehicle setPylonLoadout [4,"PylonMissile_1Rnd_Mk82_F", true];
_vehicle setPylonLoadout [5,"PylonMissile_1Rnd_Mk82_F", true];
_vehicle setPylonLoadout [6,"PylonMissile_1Rnd_Mk82_F", true];
_vehicle setPylonLoadout [7,"PylonMissile_1Rnd_Mk82_F", true];
_vehicle setPylonLoadout [8,"PylonMissile_1Rnd_Mk82_F", true];
_vehicle setPylonLoadout [9,"PylonMissile_1Rnd_Mk82_F", true];
_vehicle setPylonLoadout [10,"PylonRack_1Rnd_Missile_AA_04_F", true];
_vehicle setPylonLoadout [11,"PylonRack_1Rnd_Missile_AA_04_F", true];