params ["_vehicle"];
_vehicle setPylonLoadout [1,"PylonRack_1Rnd_Missile_AA_04_F", true];
_vehicle setPylonLoadout [2,"PylonRack_1Rnd_Missile_AA_04_F", true];
_vehicle setPylonLoadout [3,"", true];
_vehicle setPylonLoadout [4,"itc_hp_smart_ITC_ammo_gbu31", true];
_vehicle setPylonLoadout [5,"", true];
_vehicle setPylonLoadout [6,"js_m_fa18_wing_tank_x1", true];
_vehicle setPylonLoadout [7,"", true];
_vehicle setPylonLoadout [8,"itc_hp_smart_ITC_ammo_gbu31", true];
_vehicle setPylonLoadout [9,"", true];
_vehicle setPylonLoadout [10,"PylonRack_1Rnd_Missile_AA_04_F", true];
_vehicle setPylonLoadout [11,"PylonRack_1Rnd_Missile_AA_04_F", true];